name: "Stop runner"
description: "Stop a Github Runner on AWS"

inputs:
  github-token:
    description: Github Personal Access Token
    required: true

  instance-id:
    description: EC2 instance id
    required: true

  runner-label:
    description: Runner label
    required: true

  aws-access-key-id:
    description: AWS access key id
    required: false
  aws-secret-access-key:
    description: AWS secret access key
    required: false
  aws-region:
    description: AWS region
    required: false

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      if: ${{inputs.aws-access-key-id != ''}}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Stop EC2 runner
      uses: machulav/ec2-github-runner@v2
      with:
        mode: stop
        github-token: ${{ inputs.github-token }}
        label: ${{ inputs.runner-label }}
        ec2-instance-id: ${{ inputs.instance-id }}
